name: mobile_starter_2026
description: "Starter template resmi mata kuliah Pemrograman Piranti Bergerak (Clean Architecture & BLoC)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & Reactive
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Routing & Navigation
  go_router: ^14.2.0

  # Networking & Serialization
  dio: ^5.7.0
  json_annotation: ^4.9.0

  # Local Persistence & Security
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.2.1

  # UI, Icons, & Design System
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter & Quality Assurance
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
